apiVersion: v1
kind: Service
metadata:
  name: jwt-validator
spec:
  type: {{ .Values.service.type }}
  selector:
    app: jwt-validator
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 8080
